// apps/web/pages/support-us.vue
<template>
	<div class="support-page">
		<div class="page-header">
			<h1 class="page-title">Support Us</h1>
			<p class="page-sub">Your support helps us continue developing and maintaining Balatro Multiplayer</p>
		</div>

		<div class="cards-grid">
			<!-- Mod support -->
			<BPanel variant="default" class="support-card">
				<div class="card-icon" style="background: var(--bal-amber)">☕</div>
				<div class="card-body">
					<h2 class="card-title">Support the Multiplayer Mod</h2>
					<p class="card-desc">Help fund the development of the Balatro Multiplayer Mod.</p>
					<p class="card-detail">Your contribution helps add new features, fix bugs, and maintain the multiplayer experience for everyone.</p>
				</div>
				<a href="https://ko-fi.com/virtualized/shop" target="_blank" rel="noopener noreferrer" class="support-btn">
					Support on Ko-fi ↗
				</a>
			</BPanel>

			<!-- Website support -->
			<BPanel variant="default" class="support-card">
				<div class="card-icon" style="background: var(--bal-coral)">♥</div>
				<div class="card-body">
					<h2 class="card-title">Support This Website</h2>
					<p class="card-desc">Help fund the development and hosting of this website.</p>
					<p class="card-detail">Your contribution helps improve the website, add new features, and keep the servers running smoothly.</p>
				</div>
				<div class="support-btn-group">
					<a href="https://ko-fi.com/andy_balatro" target="_blank" rel="noopener noreferrer" class="support-btn">
						Support Andy on Ko-fi ↗
					</a>
					<a href="https://ko-fi.com/jeffdev" target="_blank" rel="noopener noreferrer" class="support-btn support-btn--secondary">
						Support Jeffdev on Ko-fi ↗
					</a>
				</div>
			</BPanel>

			<!-- Bot support -->
			<BPanel variant="default" class="support-card">
				<div class="card-icon" style="background: var(--bal-purple)">🤖</div>
				<div class="card-body">
					<h2 class="card-title">Support the Discord Bot</h2>
					<p class="card-desc">Help fund the development of the Botlatro Discord bot.</p>
					<p class="card-detail">Your contribution supports the developers maintaining and improving Botlatro, the bot used for the matchmaking queue on Discord.</p>
				</div>
				<a href="https://ko-fi.com/botlatro" target="_blank" rel="noopener noreferrer" class="support-btn">
					Support on Ko-fi ↗
				</a>
			</BPanel>
		</div>

		<!-- Why it matters -->
		<BPanel variant="dark" class="why-panel">
			<div class="why-icon">$</div>
			<h2 class="why-title">Why Your Support Matters</h2>
			<p class="why-body">
				Balatro Multiplayer is a community-driven project maintained by volunteers.
				Your support directly contributes to server costs, development time, and the continued
				improvement of the multiplayer experience for all players.
			</p>
		</BPanel>
	</div>
</template>

<style scoped>
.support-page {
	max-width: 900px;
	margin: 0 auto;
}

.page-header {
	text-align: center;
	margin-bottom: 40px;
}

.page-title {
	font-size: 24px;
	color: var(--bal-white);
	text-shadow: 3px 3px 0 rgba(0,0,0,0.4);
	margin-bottom: 12px;
}

.page-sub {
	font-size: 11px;
	color: var(--bal-teal-gray);
	line-height: 2;
}

.cards-grid {
	display: grid;
	grid-template-columns: repeat(3, 1fr);
	gap: 16px;
	margin-bottom: 24px;
}

.support-card {
	display: flex;
	flex-direction: column;
	gap: 16px;
}

.card-icon {
	width: 48px;
	height: 48px;
	border-radius: 12px;
	display: flex;
	align-items: center;
	justify-content: center;
	font-size: 20px;
	box-shadow: 0 3px 0 rgba(0,0,0,0.3);
	flex-shrink: 0;
}

.card-body {
	flex: 1;
}

.card-title {
	font-size: 13px;
	color: var(--bal-cream);
	margin-bottom: 8px;
	font-weight: 700;
}

.card-desc {
	font-size: 9px;
	color: var(--bal-teal-gray);
	margin-bottom: 8px;
	line-height: 2;
}

.card-detail {
	font-size: 9px;
	color: var(--bal-gray-blue);
	line-height: 2;
}

.support-btn {
	display: inline-flex;
	align-items: center;
	gap: 6px;
	background: var(--bal-coral);
	color: var(--bal-white);
	font-family: inherit;
	font-size: 11px;
	font-weight: 700;
	padding: 10px 20px;
	border-radius: 999px;
	border: none;
	cursor: pointer;
	box-shadow: 0 4px 0 var(--bal-red-dark), 0 6px 12px rgba(0,0,0,0.3);
	transition: transform 0.1s;
	text-decoration: none;
}

.support-btn:hover { color: var(--bal-white); transform: translateY(-2px); }
.support-btn:active { transform: translateY(2px); }

.support-btn--secondary {
	background: var(--bal-panel-light);
	color: var(--bal-gray-blue);
	box-shadow: 0 4px 0 var(--bal-panel-dark), 0 6px 12px rgba(0,0,0,0.3);
}

.support-btn-group {
	display: flex;
	flex-direction: column;
	gap: 10px;
}

.why-panel {
	text-align: center;
	padding: 36px !important;
}

.why-icon {
	width: 48px;
	height: 48px;
	border-radius: 50%;
	background: var(--bal-gold);
	box-shadow: 0 3px 0 var(--bal-gold-dark);
	color: var(--bal-panel-dark);
	font-size: 22px;
	font-weight: 900;
	display: flex;
	align-items: center;
	justify-content: center;
	margin: 0 auto 20px;
}

.why-title {
	font-size: 16px;
	color: var(--bal-white);
	margin-bottom: 16px;
	text-shadow: 2px 2px 0 rgba(0,0,0,0.3);
}

.why-body {
	font-size: 10px;
	color: var(--bal-teal-gray);
	max-width: 560px;
	margin: 0 auto;
	line-height: 2.2;
}

@media (max-width: 700px) {
	.cards-grid { grid-template-columns: 1fr; }
}
</style>

// apps/web/src/app/(home)/support-us/page.tsx
import {
  Bot,
  CircleDollarSign,
  Coffee,
  ExternalLink,
  Heart,
} from 'lucide-react'
import Link from 'next/link'
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from '@/components/ui/card'
import { createMetadata } from '@/lib/metadata'

export const metadata = createMetadata({
  title: 'Support Us',
  description:
    'Support Balatro Multiplayer, the website, and Botlatro to help fund hosting, development, and community tools.',
  path: '/support-us',
})

export default async function SupportUsPage() {
  return (
    <div className='mx-auto flex w-[calc(100%-1rem)] max-w-fd-container flex-1 flex-col py-8'>
      <div className={'mb-10 text-center'}>
        <h1 className={'font-bold text-4xl tracking-tight'}>Support Us</h1>
        <p className={'mt-4 text-lg text-muted-foreground'}>
          Your support helps us continue developing and maintaining Balatro
          Multiplayer
        </p>
      </div>

      <div className={'grid gap-8 md:grid-cols-3'}>
        <Card className={'transition-all hover:shadow-md'}>
          <CardHeader className={'flex flex-row items-center gap-4'}>
            <div className={'rounded-full bg-primary/10 p-2'}>
              <Coffee className={'size-6 text-primary'} />
            </div>
            <div>
              <CardTitle>Support Multiplayer Mod</CardTitle>
              <CardDescription>
                Help fund the development of the Balatro Multiplayer Mod
              </CardDescription>
            </div>
          </CardHeader>
          <CardContent>
            <p className={'text-muted-foreground'}>
              Your contribution helps us add new features, fix bugs, and
              maintain the multiplayer experience for everyone.
            </p>
          </CardContent>
          <CardFooter>
            <Link
              target={'_blank'}
              rel={'noopener noreferrer'}
              href={'https://ko-fi.com/virtualized/shop'}
              className={
                'flex items-center gap-2 rounded-md bg-primary px-4 py-2 text-primary-foreground transition-colors hover:bg-primary/90'
              }
            >
              Support on Ko-fi <ExternalLink className={'size-4'} />
            </Link>
          </CardFooter>
        </Card>

        <Card className={'transition-all hover:shadow-md'}>
          <CardHeader className={'flex flex-row items-center gap-4'}>
            <div className={'rounded-full bg-primary/10 p-2'}>
              <Heart className={'size-6 text-primary'} />
            </div>
            <div>
              <CardTitle>Support This Website</CardTitle>
              <CardDescription>
                Help fund the development and hosting of this website
              </CardDescription>
            </div>
          </CardHeader>
          <CardContent>
            <p className={'text-muted-foreground'}>
              Your contribution helps us improve the website, add new features,
              and keep the servers running smoothly.
            </p>
          </CardContent>
          <CardFooter className={'flex flex-wrap gap-2'}>
            <Link
              target={'_blank'}
              rel={'noopener noreferrer'}
              href={'https://ko-fi.com/andy_balatro'}
              className={
                'flex items-center gap-2 rounded-md bg-primary px-4 py-2 text-primary-foreground transition-colors hover:bg-primary/90'
              }
            >
              Support Andy on Ko-fi <ExternalLink className={'size-4'} />
            </Link>
            <Link
              target={'_blank'}
              rel={'noopener noreferrer'}
              href={'https://ko-fi.com/jeffdev'}
              className={
                'flex items-center gap-2 rounded-md bg-primary px-4 py-2 text-primary-foreground transition-colors hover:bg-primary/90'
              }
            >
              Support Jeffdev on Ko-fi <ExternalLink className={'size-4'} />
            </Link>
          </CardFooter>
        </Card>

        <Card className={'transition-all hover:shadow-md'}>
          <CardHeader className={'flex flex-row items-center gap-4'}>
            <div className={'rounded-full bg-primary/10 p-2'}>
              <Bot className={'size-6 text-primary'} />
            </div>
            <div>
              <CardTitle>Support the Discord Bot</CardTitle>
              <CardDescription>
                Help fund the development of the Botlatro Discord bot
              </CardDescription>
            </div>
          </CardHeader>
          <CardContent>
            <p className={'text-muted-foreground'}>
              Your contribution helps support the developers maintaining and
              improving the Botlatro Discord bot, which is used for the queue in
              discord.
            </p>
          </CardContent>
          <CardFooter>
            <Link
              target={'_blank'}
              rel={'noopener noreferrer'}
              href={'https://ko-fi.com/botlatro'}
              className={
                'flex items-center gap-2 rounded-md bg-primary px-4 py-2 text-primary-foreground transition-colors hover:bg-primary/90'
              }
            >
              Support on Ko-fi <ExternalLink className={'size-4'} />
            </Link>
          </CardFooter>
        </Card>
      </div>

      <div className={'mt-12 rounded-lg border bg-card p-6 text-center'}>
        <CircleDollarSign className={'mx-auto mb-4 size-10 text-primary/70'} />
        <h2 className={'mb-2 font-semibold text-2xl'}>
          Why Your Support Matters
        </h2>
        <p className={'mx-auto max-w-2xl text-muted-foreground'}>
          Balatro Multiplayer is a community-driven project maintained by
          volunteers. Your support directly contributes to server costs,
          development time, and the continued improvement of the multiplayer
          experience for all players.
        </p>
      </div>
    </div>
  )
}
